PixabitSolutionsMvc/Models/FeedbackForm.cs
using System.ComponentModel.DataAnnotations;
using PixabitSolutionsMvc.Resources;


namespace PixabitSolutionsMvc.Models
{
    public class FeedbackForm
    {
        [StringLength(50, ErrorMessageResourceType = typeof(Translations), ErrorMessageResourceName = "StringLengthMaximum")]
        [Required(ErrorMessageResourceType = typeof(Translations), ErrorMessageResourceName = "NameLabel")]
        public string Name { get; set; }

        [StringLength(100, ErrorMessageResourceType = typeof(Translations), ErrorMessageResourceName = "StringLengthMaximum")]
        [Required(ErrorMessageResourceType = typeof(Translations), ErrorMessageResourceName = "EmailLabel")]
        [RegularExpression(@"^([a-zA-Z0-9_\.\-])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$", ErrorMessageResourceType = typeof(Translations), ErrorMessageResourceName = "EmailValidation")]
        public string Email { get; set; }

        [Required(ErrorMessageResourceType = typeof(Translations), ErrorMessageResourceName = "MessageLabel")]
        [DataType(DataType.MultilineText)]
        public string Message { get; set; }

        [Required(ErrorMessageResourceType = typeof(Translations), ErrorMessageResourceName = "CaptchaEmptyField")]
        [Range(0, 1000, ErrorMessageResourceType = typeof(Translations), ErrorMessageResourceName = "CaptchaRange")]
        public string Captcha { get; set; } 
    }
        
}

PixabitSolutionsMvc/Models/LanguageCultureViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PixabitSolutionsMvc.Models
{
    public class LanguageCultureViewModel
    {

        public LanguageCultureViewModel(string code, string desc)
        {
            Code = code;
            Description = desc;
        }
        public string Code { get; private set; }
        public string Description { get; private set; }
    }
}

PixabitSolutionsMvc/Controllers/CareerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PixabitSolutionsMvc.Controllers
{
    public class CareerController : Controller
    {
        //
        // GET: /Career/
        public ActionResult DotNetDeveloper()
        {
            return View();
        }

        public ActionResult BusinessAnalyst()
        {
            return View();
        }
	}
}

PixabitSolutionsMvc/Controllers/HomeController.cs
using System;
using System.Web.Mvc;
using PixabitSolutionsMvc.Infrastructure;
using PixabitSolutionsMvc.Models;
using PixabitSolutionsMvc.Resources;
using System.Drawing;
using System.IO;
using  System.Drawing.Drawing2D;
using  System.Drawing.Text;

namespace PixabitSolutionsMvc.Controllers
{
 
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult SwitchLanguage(string lang, string returnUrl)
        {
           LanguageCultureHelper.SetLanguageCultureCookie(lang);
           return Redirect(string.IsNullOrEmpty(returnUrl) ? "~/" : returnUrl);//save current Url for translation
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }
    
        [HttpGet]
        public ActionResult Contact()
        {

            ViewBag.Message = "Your contact page.";
            var temp = new FeedbackForm();
            return View(temp);
        }

        [HttpPost]
        public ActionResult Contact(FeedbackForm model)
        {
            var rez = new EmailBodyGenerator(model);
            var text = rez.GenerateEmailBody();
            var tempForm = new FeedbackForm();

            if (Session["Captcha"].ToString() != model.Captcha )
            {
                ModelState.AddModelError("Captcha", Translations.CaptchaValidation);
                return View();
            }

            try
            {
                EmailSender.SendEmail(AppSettings.FromEmailAddress, AppSettings.ToEmailAddress, Translations.Contact_Form_Message_Field, text);
                ViewBag.SendContactSuccess = Translations.SubmitSuccess;
                ModelState.Clear();
            }

            catch (Exception)
            {
                ViewBag.SmtpError = Translations.SmtpError;

            }

            if (Session["Captcha"] == null)
            {
                return RedirectToAction("Contact", "Home");
            }
       
            return View(tempForm);  
        }

        [HttpGet]
        public ActionResult CaptchaImage(string prefix, bool noisy = true)
        {

            var rand = new Random((int) DateTime.Now.Ticks);
            //generate new question
            var a = rand.Next(10, 99);
            var b = rand.Next(0, 9);
            var captcha = string.Format("{0} + {1} = ?", a, b);

            //store answer
            Session["Captcha" + prefix] = a + b;

            //image stream
            FileContentResult img = null;

            using (var mem = new MemoryStream())
            using (var bmp = new Bitmap(130, 30))
            using (var gfx = Graphics.FromImage((Image)bmp))
            {
                gfx.TextRenderingHint = TextRenderingHint.ClearTypeGridFit;
                gfx.SmoothingMode = SmoothingMode.AntiAlias;
                gfx.FillRectangle(Brushes.White, new Rectangle(0, 0, bmp.Width, bmp.Height));

       
                //add noise
                if (noisy)
                {
                    int i;
                    var pen = new Pen(Color.Yellow);
                    for (i = 1; i < 10; i++)
                    {
                        pen.Color = Color.FromArgb(
                            (rand.Next(0, 255)),
                            (rand.Next(0, 255)),
                            (rand.Next(0, 255)));

                        var r = rand.Next(0, (130 / 3));
                        var x = rand.Next(0, 130);
                        var y = rand.Next(0, 30);

                        gfx.DrawEllipse(pen, x - r, y - r, r, r);
                    }
                }

                //add question
                gfx.DrawString(captcha, new Font("Tahoma",15), Brushes.DimGray, 2, 3);

                //render as Jpeg
                bmp.Save(mem, System.Drawing.Imaging.ImageFormat.Jpeg);
                img = this.File(mem.GetBuffer(), "image/Jpeg");

            }

            return img;
        }

        public ActionResult Impressum()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }
     
    }
}

PixabitSolutionsMvc/Controllers/PortfolioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PixabitSolutionsMvc.Controllers
{
    public class PortfolioController : Controller
    {
        //
        // GET: /Portfolio/
        public ActionResult ResponsiveProjects()
        {
            ViewBag.Message = "Our projects";

            return View();
        }

        public ActionResult NotResponsiveProjects()
        {
            ViewBag.Message = "Our projects";

            return View();
        }
	}
}

PixabitSolutionsMvc/Controllers/ProjectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PixabitSolutionsMvc.Controllers
{
    public class ProjectsController : Controller
    {
        //
        // GET: /Projects/
        public ActionResult OurCustomers()
        {
            ViewBag.Message = "Our customers";

            return View();
        }
	}
}

PixabitSolutionsMvc/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PixabitSolutionsMvc.Controllers
{
    public class ServicesController : Controller
    {
        //
        // GET: /Services/
        public ActionResult SoftwareDevelopment()
        {
            ViewBag.Message = "Software development";

            return View();
        }

        public ActionResult DotNetDevelopment()
        {
            ViewBag.Message = ".Net development";

            return View();
        }

        public ActionResult WebDevelopment()
        {
            ViewBag.Message = "Web development";

            return View();
        }

        
	}
}

PixabitSolutionsMvc/Views/Career/DotNetDeveloper.cshtml
@{
    ViewBag.Title = "DotNetDeveloper";
}

<header class="main-header">
    <div class="container">
        <h1 class="page-title">ASP.NET Developer</h1>
        <ol class="breadcrumb pull-right">
            <li>About us</li>
            <li>Career</li>
            <li class="active">ASP.NET Developer</li>
        </ol>
    </div>
</header>

<div class="container body-content">
    <h2 class="right-line">ASP.NET Developer</h2>
    <article>
        <p>
            We are looking for ASP.NET Intermediate/Senior Backend/Frontend developers (m/f) to join our team in Kiev.
            You will develop web and mobile commercial solutions for our international customers with latest technologies like VisualStudio 2013, KendoUI and HTML5.
        </p>

        <!-- Nav tabs -->
        <ul class="nav nav-tabs nav-tabs-ar nav-tabs-ar-white">
            <li class="active"><a href="#requirements" data-toggle="tab">Basic requirements</a></li>
            <li><a href="#skills" data-toggle="tab">Desired skills</a></li>
            <li><a href="#offer" data-toggle="tab">We offer</a></li>
        </ul>

        <!-- Tab panes -->
        <div class="tab-content">
            <div class="tab-pane active" id="requirements">
                <ul>
                    <li>ASP.NET - 3 years .NET - 5 years</li>
                    <li>MVC, HTML5</li>
                    <li>OOP principles, design patterns</li>
                    <li>Javascript, jQuery, CSS</li>
                    <li>Intermediate spoken English</li>
                    <li>Unit testing</li>
                    <li>Team working, Agile methods, Scrum</li>
                </ul>
            </div>
            <div class="tab-pane" id="skills">
                <ul>
                    <li>SQL</li>
                    <li>KendoUI Web, KendoUI Mobile</li>
                    <li>Devexpress components</li>
                    <li>WCF</li>
                    <li>Entity Framework</li>
                    <li>German language</li>
                </ul>
            </div>
            <div class="tab-pane" id="offer">
                <ul>
                    <li>Excellent 'white' compensation package</li>
                    <li>As well as good opportunities for career and personal development</li>
                    <li>Exciting projects involving newest technologies</li>
                    <li>Medical insurance</li>
                    <li>24 days vacation</li>
                    <li>German language course</li>
                    <li>Possible relocation to Germany</li>
                </ul>
            </div>
        </div>
    </article>
</div>

PixabitSolutionsMvc/Views/Home/Index.de.cshtml
@{
    ViewBag.Title = "Home Page";
}

<header class="services-header">
    <div class="primary-dark-div">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="service-header-text text-center">
                        <h1 class="animated fadeInDown animation-delay-2">Pixabit solutions GmbH</h1>
                        <p class="animated fadeInDown animation-delay-5">Wir entwickeln individuelle software für Unternehmen und öffentliche Einrichtungen mit den neuesten Technologien</p>
                    </div>
                </div>
                <div class="col-md-6">
                    <ul class="services-header-list">
                        <li class="animated fadeInUp animation-delay-5"><a href="@Url.Action("DotNetDevelopment", "Services")"><i class="fa fa-globe"></i>Know-how für Microsoft .NET, WPF und ASP.NET</a></li>
                        <li class="animated fadeInUp animation-delay-8"><a href="@Url.Action("WebDevelopment", "Services")"><i class="fa fa-html5"></i>Internet und Mobile</a></li>
                        <li class="animated fadeInUp animation-delay-11"><a href="#"><i class="fa fa-cloud"></i>Verwaltung, ITK, Infrastruktur, Service, Support</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="container body-content">
    <article>
        <p>
            Die <strong>Pixabit solutions GmbH</strong> entwickelt mit modernsten Technologien <strong>individuelle Software für Unternehmen aller Branchen und öffentliche Auftraggeber</strong>. Kundenspezifische Anwendungen schaffen Kosten- und Wettbewerbsvorteile dort, wo Standardsoftware an Grenzen stößt.
            Wir begleiten unsere Kunden von der Bedarfsermittlung bis zum Roll-Out mit umfassender Entwicklungskompetenz, fairen Konditionen und termintreuer Ausführung.
        </p>
        <p>
            Als <strong>Lieferant für Softwarehäuser</strong> und Agenturen bieten wir <strong>Projektunterstützung als externe Spezialisten in .NET (C#, WPF, XAML, ASP.NET, T-SQL)</strong> sowie Java EE- und Frontendtechnologien.
        </p>
        <p>
            Mit unserem <strong>übergreifenden Know-How</strong> in angrenzende Bereiche wie <strong>Security, Systeme, Internet & Cloud</strong> begleiten wir unsere Kunden nicht nur in der Softwareentwicklung, sondern auch beim Applikationsbetrieb, der Wartung und Support unserer Entwicklungen.
        </p>
        <p>
            <a href="@Url.Action("OurCustomers", "Projects")">Unsere Kunden </a> <strong>schätzen</strong> an uns
            <ul>
                <li>unser <strong>kompetentes und leistungsfähiges</strong> Entwickler- und Test-Team</li>
                <li>unsere <strong>Flexibilität </strong> hinsichtlich Technologien, Lösungsmöglichkeiten und zeitliche Verfügbarkeit</li>
                <li>unsere <strong>Lösungsorientierung</strong> mit hohem <strong>Kosten-Nutzen-Verständnis</strong></li>
            </ul>
            
        <p>
            <i>Schätzen Sie diese Werte auch? Nehmen Sie <a href=@Url.Action("Contact", "Home")>Kontakt</a> mit uns auf - wir freuen uns über Ihre Anfrage!</i>
        </p>
    </article>
    <aside class="col-xs-4 text-icon">
        <span class="icon-ar icon-ar-lg">
            <i class="fa fa-laptop"></i> 
        </span>
    
        <div class="text-icon-content"><h3>Software-Entwicklung</h3></div>
        <p><strong>Pixabit solutions GmbH</strong> leistet <strong>Softwareentwicklung für Unternehmen und öffentliche Auftraggeber</strong>. Wir entwickeln individuelle Software mit modernsten Technologien.</p>
            <ul>
                <li>Microsoft .NET, C#</li>
                <li>Java EE Anwendungen</li>
                <li>Moderne Webanwendungen mit ASP.NET in MVC-Architektur</li>
                <li>HTML5 Webanwendungen mit z.B. Kendo UI Web und Kendo UI Mobile</li>
                <li>UI Konzeption und Responsive Design</li>
                <li>Anspruchsvolle Desktopanwendungen mit WPF (Windows Presentation Foundation) und MVVM</li>
                <li>Erstellung von UIs mit XAML für WPF</li>
                <li>Clean Code Entwicklung</li>
                <li>T-SQL, SQL- Unterstützung</li>
                <li>Server- und Cloudgestützte Lösungen</li>
                <li>Mobile Lösungen (iOS, Android, Hybrid, HTML5)</li>
            </ul>
      
    </aside>
    <aside class="col-xs-4 text-icon ">
        <span class="icon-ar icon-ar-lg">
            <i class="fa fa-hand-o-down"></i>
        </span>
        <div class="text-icon-content">
            <h3>Ihr Bedarf</h3>
        </div>
        <p>Sie benötigen Projektunterstützung und Ressourcen für die Umsetzung Ihrer Software-Ideen?</p>
        <p>Sie haben eine IT-Herausforderung wissen aber nicht wie Sie dies lösen können?</p>
        <p>Ihre Idee lässt sich nicht mit Ihrer Standardsoftware lösen?</p>
        <ul>
            <li><b>Projektunterstützung:</b> Externe Leistung durch unser Entwicklerteam oder Inhouse-Unterstützung</li>
            <li><b>Scrum-Team:</b> Als eingespieltes Scrum-Team mit zertifierten Product Owner und Scrum Master unterstützen wir Sie als externes agiles Projektteam</li>
            <li><b>Bedarfsermittlung:</b> Wir ermitteln mit Ihnen Ihren Bedarf - gerade dann wenn Sie kein "IT" sprechen</li>
            <li><b>Beratung:</b> Wir beraten Sie hinsichtlich Softwarearchitekturen</li>
            <li><b>Implementierung:</b> Wir unterstützen Sie in der Softwareentwicklung mit unserem Team</li>
            <li><b>Betrieb und Support:</b> Greifen Sie auf unsere Unterstützung für Betrieb, Support und Wartung Ihrer Anwendung zurück</li>
        </ul>
    </aside>
    <aside class="col-xs-4 text-icon">
        <span class="icon-ar icon-ar-lg">
            <i class="fa fa-thumbs-o-up"></i>
        </span>
        <div class="text-icon-content">
            <h3>Unsere Lösungen</h3>
        </div>
        <p>Werfen Sie einen Blick auf unsere Lösungen und Beispiele, von denen unsere Kunden erfolgreich profitiert haben:</p>
        <ul>
            <li>Individuelle CRM-Lösungen (Customer Relationship Management)</li>
            <li>Moderne Desktop- und Webanwendungen mit .NET Technologie</li>
            <li>Entwicklung, Bereitstellung und Hosting von Webservices (z.B. SOAP, REST, WCF)</li>
            <li>Tools und (Office-)Anwendungen zur Optimierung des betrieblichen Ablaufs</li>
            <li>Schnittstellen zwischen verschiedenen Standard- und Websystemen</li>
            <li>Individuelle Entwicklungen und Schnittstellen im Zusammenhang mit SAP oder anderen ERP- oder CRM-Systemen</li>
            <li>Datenmigrationen</li>
        </ul>
</aside>
</div>

PixabitSolutionsMvc/Views/Shared/_MainMenu.cshtml
<nav class="navbar navbar-static-top navbar-default navbar-header-full navbar-dark" role="navigation" id="header" >
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <i class="fa fa-bars"></i>
            </button>
        </div> <!-- navbar-header -->
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav" >
                <li >
                    <a href="@Url.Action("Index", "Home")">Home</a>
                    @*<ul class="dropdown-menu dropdown-menu-left">
                <li role="presentation" class="dropdown-header">Example</li>
                <li><a href="configurator.html">Example<span class="label label-success pull-right">New</span></a></li>
            </ul>*@
                </li>
                <li class="dropdown">
                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" >About us</a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="@Url.Action("About", "Home")">Pixabit Solutions</a>
                        </li>
                        <li class="dropdown-submenu">
                            <a href="javascript:void(0);" class="has_children">Career</a>
                            <ul class="dropdown-menu">
                                <li><a href="@Url.Action("DotNetDeveloper", "Career")">ASP.NET developer</a></li>
                                <li><a href="@Url.Action("BusinessAnalyst", "Career")" >Business Analyst with German</a></li>
                                @*<li><a href="#">QA Engineer with German</a></li>*@
                            </ul>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">Services</a>
                    <ul class="dropdown-menu">
                        <li><a href="@Url.Action("SoftwareDevelopment", "Services")">Software development</a></li>
                        <li><a href="@Url.Action("DotNetDevelopment", "Services")">.NET development</a></li>
                        <li><a href="@Url.Action("WebDevelopment", "Services")" >Web development</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">Projects</a>
                    <ul class="dropdown-menu">
                        <li><a href="@Url.Action("OurCustomers", "Projects")" >Customers</a></li>
                        <li class="dropdown-submenu">
                            <a href="javascript:void(0);" class="has_children" >Portfolio</a>
                            <ul class="dropdown-menu dropdown-menu-left">
                                <li><a href="@Url.Action("ResponsiveProjects", "Portfolio")" >Device projects</a></li>
                                <li><a href="@Url.Action("NotResponsiveProjects", "Portfolio")" >Projects</a></li>
                            </ul>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="@Url.Action("Contact", "Home")">Contacts</a>
                </li>
                <li>
                    <a href="@Url.Action("Impressum", "Home")">Legal Notice</a>
                </li>
            </ul>
        </div><!-- navbar-collapse -->
    </div><!-- container -->
</nav>

PixabitSolutionsMvc/Views/Shared/_MainMenu.de.cshtml
<nav class="navbar navbar-static-top navbar-default navbar-header-full navbar-dark" role="navigation" id="header" style="font-size: 12px; font-family: Arial">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <i class="fa fa-bars"></i>
            </button>
        </div> <!-- navbar-header -->
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li>
                    <a href="@Url.Action("Index", "Home")">Home</a>
                    @*<ul class="dropdown-menu dropdown-menu-left">
                            <li role="presentation" class="dropdown-header">Example</li>
                            <li><a href="configurator.html">Example<span class="label label-success pull-right">New</span></a></li>
                        </ul>*@
                </li>
                <li class="dropdown">
                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">Über uns</a>
                    <ul class="dropdown-menu dropdown-menu-left">
                        <li>
                            <a href="@Url.Action("About", "Home")">Pixabit Solutions</a>
                        </li>
                        <li class="dropdown-submenu">
                            <a href="javascript:void(0);" class="has_children">Karriere</a>
                            <ul class="dropdown-menu dropdown-menu-left">
                                <li><a href="@Url.Action("DotNetDeveloper", "Career")">ASP.NET Entwickler</a></li>
                                <li><a href="@Url.Action("BusinessAnalyst", "Career")">Business Analyst mit deutschen</a></li>
                                @*<li><a href="#">QA Engineer with German</a></li>*@
                            </ul>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">Service</a>
                    <ul class="dropdown-menu dropdown-menu-left">
                        <li><a href="@Url.Action("SoftwareDevelopment", "Services")">Software-Entwicklung</a></li>
                        <li><a href="@Url.Action("DotNetDevelopment", "Services")">.NET-Entwicklung</a></li>
                        <li><a href="@Url.Action("WebDevelopment", "Services")">Web-Entwicklung</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">Projekte</a>
                    <ul class="dropdown-menu dropdown-menu-left">
                        <li><a href="@Url.Action("OurCustomers", "Projects")">Kunden</a></li>
                        <li class="dropdown-submenu">
                            <a href="javascript:void(0);" class="has_children">Portfolio</a>
                            <ul class="dropdown-menu dropdown-menu-left">
                                <li><a href="@Url.Action("ResponsiveProjects", "Portfolio")">Gerät Projekte</a></li>
                                <li><a href="@Url.Action("NotResponsiveProjects", "Portfolio")">Projekte</a></li>
                            </ul>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="@Url.Action("Contact", "Home")">Kontakt</a>
                </li>
                <li>
                    <a href="@Url.Action("Impressum", "Home")">Impressum</a>
                </li>
            </ul>
        </div><!-- navbar-collapse -->
    </div><!-- container -->
</nav>

PixabitSolutionsMvc/Views/Shared/_MainMenu.ru.cshtml
<nav class="navbar navbar-static-top navbar-default navbar-header-full navbar-dark" role="navigation" id="header" style="font-size: 12px; font-family: Arial">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <i class="fa fa-bars"></i>
            </button>
        </div> <!-- navbar-header -->
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li>
                    <a href="@Url.Action("Index", "Home")"><i class="icon-home"></i>Главная</a>
                    @*<ul class="dropdown-menu dropdown-menu-left">
                            <li role="presentation" class="dropdown-header">Example</li>
                            <li><a href="configurator.html">Example<span class="label label-success pull-right">New</span></a></li>
                        </ul>*@
                </li>
                <li class="dropdown">
                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">О нас</a>
                    <ul class="dropdown-menu dropdown-menu-left">
                        <li>
                            <a href="@Url.Action("About", "Home")">Pixabit Solutions</a>
                        </li>
                        <li class="dropdown-submenu">
                            <a href="javascript:void(0);" class="has_children">Карьера</a>
                            <ul class="dropdown-menu dropdown-menu-left">
                                <li><a href="@Url.Action("DotNetDeveloper", "Career")">ASP.NET разработчик</a></li>
                                <li><a href="@Url.Action("BusinessAnalyst", "Career")">Немецкий бизнес аналитик</a></li>
                                @*<li><a href="#">QA Engineer with German</a></li>*@
                            </ul>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">Услуги</a>
                    <ul class="dropdown-menu dropdown-menu-left">
                        <li><a href="@Url.Action("SoftwareDevelopment", "Services")">Разработка програмного обеспечения</a></li>
                        <li><a href="@Url.Action("DotNetDevelopment", "Services")">.NET разработка</a></li>
                        <li><a href="@Url.Action("WebDevelopment", "Services")">Web-разработка</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown">Проекты</a>
                    <ul class="dropdown-menu dropdown-menu-left">
                        <li><a href="@Url.Action("OurCustomers", "Projects")">Клиенты</a></li>
                        <li class="dropdown-submenu">
                            <a href="javascript:void(0);" class="has_children">Портфолио</a>
                            <ul class="dropdown-menu dropdown-menu-left">
                                <li><a href="@Url.Action("ResponsiveProjects", "Portfolio")">Проекты для устройств</a></li>
                                <li><a href="@Url.Action("NotResponsiveProjects", "Portfolio")">Проекты</a></li>
                            </ul>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="@Url.Action("Contact", "Home")">Контакты</a>
                </li>
                <li>
                    <a href="@Url.Action("Impressum", "Home")">Юридическая информация</a>
                </li>
            </ul>
        </div><!-- navbar-collapse -->
    </div><!-- container -->
</nav>